In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[2.6078e+38, 4.5769e-41, 1.8196e-14],
        [3.0688e-41, 1.8196e-14, 3.0688e-41],
        [1.8196e-14, 3.0688e-41, 1.1431e+27],
        [2.7945e+20, 2.2419e+20, 9.8807e+17],
        [4.4653e+30, 3.4593e-12, 7.4086e+28]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.4628, 0.0105, 0.8818],
        [0.3386, 0.9230, 0.4807],
        [0.7028, 0.1410, 0.9485],
        [0.6940, 0.3933, 0.2420],
        [0.7692, 0.0685, 0.0197]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4292,  0.7075, -0.1731],
        [ 1.2939, -1.4409,  0.9076],
        [-1.3626,  0.2298,  0.9729],
        [-0.3588,  0.1044, -0.9012],
        [ 0.2411,  0.7135, -1.2718]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.2791,  0.8582,  0.0464],
        [ 1.3744, -1.2283,  1.6616],
        [-1.2917,  0.9012,  1.4427],
        [ 0.3107,  0.6157, -0.7276],
        [ 0.9814,  1.0914, -0.4756]])


In [9]:
print(torch.add(x,y))

tensor([[-0.2791,  0.8582,  0.0464],
        [ 1.3744, -1.2283,  1.6616],
        [-1.2917,  0.9012,  1.4427],
        [ 0.3107,  0.6157, -0.7276],
        [ 0.9814,  1.0914, -0.4756]])


In [10]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[-0.2791,  0.8582,  0.0464],
        [ 1.3744, -1.2283,  1.6616],
        [-1.2917,  0.9012,  1.4427],
        [ 0.3107,  0.6157, -0.7276],
        [ 0.9814,  1.0914, -0.4756]])


In [11]:
y.add_(x)
print(y)

tensor([[-0.2791,  0.8582,  0.0464],
        [ 1.3744, -1.2283,  1.6616],
        [-1.2917,  0.9012,  1.4427],
        [ 0.3107,  0.6157, -0.7276],
        [ 0.9814,  1.0914, -0.4756]])


In [12]:
y += x

In [13]:
print(y)

tensor([[-0.7083,  1.5658, -0.1267],
        [ 2.6683, -2.6692,  2.5692],
        [-2.6543,  1.1311,  2.4157],
        [-0.0481,  0.7201, -1.6288],
        [ 1.2224,  1.8049, -1.7474]])


In [14]:
print(x[:,1])

tensor([ 0.7075, -1.4409,  0.2298,  0.1044,  0.7135])


In [15]:
print(x)

tensor([[-0.4292,  0.7075, -0.1731],
        [ 1.2939, -1.4409,  0.9076],
        [-1.3626,  0.2298,  0.9729],
        [-0.3588,  0.1044, -0.9012],
        [ 0.2411,  0.7135, -1.2718]])


In [16]:
print(x[:,0])

tensor([-0.4292,  1.2939, -1.3626, -0.3588,  0.2411])


In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3127])
-0.3126923441886902


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
a.add_(3)
print(a)
print(b)

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
